name: Generate a CycloneDX SBOM with pipenv and uploads it
description: |
  Utilizes https://github.com/CycloneDX/cyclonedx-python to generate a SBOM. This SBOM will then be archived and uploaded to Github.

  Prerequisite: `pipenv install -d cyclonedx-bom`

inputs:
  publish:
    description: "Publish SBOM to Github"
    required: false
    default: "false"
  report-retention-days:
    description: Duration in days to preserve reports.
    required: true
    default: "5"
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the root project is located.
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Action context
      shell: bash
      id: context
      run: |
        working_directory=$(realpath ${{ inputs.working-directory }})
        echo "::set-output name=working-directory::$working_directory"
        echo "::set-output name=bom-path::$working_directory/build/reports/bom.json"

    - name: Generate BOM
      shell: bash
      working-directory: ${{ steps.context.outputs.working-directory }}
      run: |
        mkdir -p build/reports
        pipenv run cyclonedx-bom --pip --format json -o "${{ steps.context.outputs.bom-path }}"

    - name: Archive BOM
      uses: actions/upload-artifact@v3
      if: "!cancelled()"
      with:
        name: bom.json
        retention-days: ${{ inputs.report-retention-days }}
        path: ${{ steps.context.outputs.bom-path }}

    - name: Upload BOM
      uses: evryfs/sbom-dependency-submission-action@v0.0.11
      with:
        sbom-files: ${{ steps.context.outputs.bom-path }}
